apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: fluentd-logging
  namespace: efk
  labels:
    k8s-app: fluentd-logging
    version: v1
spec:
  template:
    metadata:
      name: fluentd-logging
      namespace: efk
      labels:
        k8s-app: fluentd-logging
    spec:
      serviceAccountName: fluentd
      containers:
      - name: fluentd-logging
        image: <YOUR_FLUENTD_IMAGE>
        env:
          - name:  FLUENT_ELASTICSEARCH_HOST
            value: "elasticsearch"
          - name:  FLUENT_ELASTICSEARCH_PORT
            value: "9200"
        volumeMounts:
        - name: varlog
          mountPath: /var/log/
          readOnly: true
        - name: varlibdockercontainers
          mountPath: /var/lib/docker
          readOnly: true
        - name: fluentdposfiles
          mountPath: /var/lib/fluentd
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log/
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker
      - name: fluentdposfiles
        hostPath:
          path: /tmp/fluentd